# Explanations of all possible options:
#   https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Naming/FileName:
  Exclude:
    - 'lib/pry-linenoise.rb'

Layout/IndentHeredoc:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
